use_frameworks!

platform :ios, '10.0'

target 'IntegratedColorPicker_Example' do
  pod 'IntegratedColorPicker', :path => '../'

  target 'IntegratedColorPicker_Tests' do
    inherit! :search_paths

    
  end
end
